name: R-CMD-check

on:
  push:
    branches: [master, SSPm]
  pull_request:
    branches: [master, SSPm]
  workflow_dispatch:

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install R package dependencies
        run: |
          Rscript -e 'install.packages(c("devtools", "roxygen2", "rmarkdown"))'
          Rscript -e 'devtools::install_deps(dependencies = TRUE)'

      - name: Check package
        run: |
          R CMD build .
          PKG_TAR=$(ls -1t *.tar.gz | head -n 1)
          R CMD check --as-cran "$PKG_TAR"

      - name: Show check results if failed
        if: failure()
        run: |
          find . -name '*00check.log' -exec cat '{}' \;
